# Application Name
spring:
  application:
    name: app
logging:
  file: logs
com:
  alipay:
    sofa:
      boot:
        disable-jvm-first: false
        skip-jvm-reference-health-check: true
        skip-extension-health-check: true
      rpc:
        registry-address: consul://127.0.0.1:8500
        bolt-port: 12345
server:
  port: 8089